[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000282429D0250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/31f2b0c3a4b4d5fe3d916a1f4cac7e22
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000282429D00D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/31f2b0c3a4b4d5fe3d916a1f4cac7e22
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000282429D3160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/31f2b0c3a4b4d5fe3d916a1f4cac7e22
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000282429D2E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b70b320c5bfea0f14184e556aedc5f65
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000282429D2B30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b70b320c5bfea0f14184e556aedc5f65
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000282429D15A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b70b320c5bfea0f14184e556aedc5f65
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028243A32470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4a4c195883103944a59129e894ea2a48
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028243A32530>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4a4c195883103944a59129e894ea2a48
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028243A326B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4a4c195883103944a59129e894ea2a48